### ISSUE TITLE
Correção do formato

### ISSUE THREAD

**Issue by lucasvmx** [lucas-engen/wordlist#1]
Corrija a forma em que os números estão sendo impressos na tela

![image](https://user-images.githubusercontent.com/13322110/59325360-bfb5b480-8cb0-11e9-96cf-c2949ca83099.png)

Eles estão sendo impressos com vírgula e parênteses, sendo que o ideal seria imprimir um ao lado do outro.

**Comment by elyakimklettke** [comment]
ok
