### ISSUE TITLE
Criar wordlist de MAC address

### ISSUE THREAD

**Issue by lucasvmx** [lucas-engen/wordlist#2]
Adicionar ao programa uma ferramente que gere todos endereços MAC possíveis (de **00:00:00:00:00:00** até **FF:FF:FF:FF:FF:FF**). Os endereços MAC gerados devem ser salvos em um arquivo e o usuário deve escolher o intervalo dos endereços a serem gerados através da linha de comando. Os caracteres **":"** devem ser removidos da geração de endereços possíveis. Exemplo de uso do programa para gerar wordlists: **python3 wordlist.py --generate-mac --start-mac=00:15:FF:AB:32:1A --end-mac=00:15:FF:FF:33:1A**

**Comment by elyakimklettke** [comment]
ok

**Comment by lucasvmx** [comment]
Implementação parcial no commit 692f9207034231a91246c40f6ca85634ee56944a
